### ISSUE TITLE
O que colocar em linguagem no caso de projetos como o Lista Maravilhosa de Projetos Open-source

### ISSUE THREAD

**Issue by camilatigre** [camilatigre/listamaravilhosaopensource#1]
Alguns projetos são apenas listas e não possuem linguagem específica.

**Comment by woliveiras** [comment]
Linguagem markdown pra editar os arquivos .md. :smile:

**Comment by camilatigre** [comment]
isso! depois que eu descobri como se chamava. achei até que tinha criado uma área de conhecimentos necessários e colocado o link haha. Obrigada pelos helps :smile:

**Comment by woliveiras** [comment]
\o/

É nozes!
