### ISSUE TITLE
Manter o link em ptbr ou mudar para awseome-opensource

### ISSUE THREAD

**Issue by camilatigre** [camilatigre/listamaravilhosaopensource#11]
Em um grupo do facebook [@jhonnymoreira](https://github.com/jhonnymoreira) sugeriu a troca do link para abranger o worldwide. Eu pensei em manter em ptbr mas queria mais opniões.

**Comment by fititnt** [comment]
Na **minha opinião**, se você pretende realmente abranger possivelmente um público que ainda não contribui para open source, deveria manter em português ou, no mínimo, deixar já no início do projeto em Português antes de aparecer qualquer coisa em Inglês.

Tem muitas pessoas iniciantes que não sabem inglês, e outras que até não são iniciantes, mas não se sentem confiantes o suficiente. Estou dizendo isso por experiência ao conversar com pessoas que estão contribuindo no https://github.com/pokemongovet

Agora, se o foco é quem é desenvolvedor com experiência média ou melhor, tanto faz.

Mas o que é certo é o seguinte: **desenvolvedores do Brasil e outros países da língua portuguesa podem saber inglês também, mas português todos sabem**. O fato de trocar o titulo do repositório pode levar a fazer alterações também no texto e, potencialmente, reduzir chance de conversão nas contribuições por elevar o nível de ansiedade.
