### ISSUE TITLE
Logo do projeto

### ISSUE THREAD

**Issue by kvnol** [camilatigre/listamaravilhosaopensource#117]
@camilatigre fiz um logo para o projeto, olha só:

![image](https://user-images.githubusercontent.com/3299130/78830632-a6f45900-79be-11ea-9f24-21b8c18121f1.png)

![image](https://user-images.githubusercontent.com/3299130/78830653-b1aeee00-79be-11ea-9d2c-c16698254d72.png)

**Comment by camilatigre** [comment]
MEU DEUS QUE COISA MAIS LINDA! E Roxa é minha cor favorita!

**Comment by kvnol** [comment]
@camilatigre sou apaixonado por roxo também, kkkk

**Comment by camilatigre** [comment]
aaaa beleza. eu não sei se tu viu mas to começando uma interface pro projeto, vou deixar salvando em um json por enquanto mas vai ter filtro e tal pra facilitar, essa logo veio em ótima hora ((:

**Comment by camilatigre** [comment]
@kvnol não consegui abrir, tem que me dar permissão, não?

**Comment by kvnol** [comment]
@camilatigre ai, verdade. dei permissão, foi mal kkk
