### ISSUE TITLE
Sugestão de workflow pra verificação de links

### ISSUE THREAD

**Issue by LeandroLS** [camilatigre/listamaravilhosaopensource#154]
Olá.
Criei uma Github Action que verifica se os links do README.md funciona. Talvez seja útil pra esse repositório.
Super simples de usar, se achar que vale a pena, segue o link:
https://github.com/LeandroLS/linksnitch

**Comment by camilatigre** [comment]
Que legal! fica a vontade pra implementar aqui tb se eu não fizer antes ((:

**Comment by LeandroLS** [comment]
Pensei em implementar, porém, após implementado ele vai ficar "reclamando" dos links quebrados que estão no README.md. Acho que faz sentido implementar apenas se o mantenedor do projeto concorde em remover links quebrados.
