### ISSUE TITLE
Uso de "pt-br" e "en" não é claro o suficiente

### ISSUE THREAD

**Issue by fititnt** [camilatigre/listamaravilhosaopensource#18]
O que significa "pt-br"? O que significa "en"?

Se "pt-br" significa "Português do Brasil" porque não por "Português do Brasil"?

E, se é "Português do Brasil" só porque o Brasil é um dos maiores países que falam Português, é necessário excluir todos os outros países que falam essa língua? Vale a pena excluir 8 países do mundo?

**Comment by camilatigre** [comment]
@fititnt acho que ptbr e en é bem básico de se entender. São abreviações comumente usadas. Quanto a  abranger outros idiomas: claro! Só que a gente está trabalhando com um projeto com 3 dias de vida, onde os projetos listados são em pt-br. Se você encontrar projetos com outras linguagens sinta-se a vontade pra abrir um PR, adicionar a linguagem no nível de dificuldade adequado [seguindo a documentação](https://github.com/camilatigre/listamaravilhosaopensource/blob/master/meu-projeto.md)

**Comment by fititnt** [comment]
Você tem certeza que "pt-br" é mais fácil de compreender do que "Português do Brasil"?

E "en", tem certeza que é mais fácil de compreender e não deixar margem do que usar o idioma completo?

Eu deduzi que "pt-br" era "Português do Brasil" mas eu moro no Brasil, e já sou programador. Porém, eu olho para os nomes que estão em inglês na lista dos que estão em "iniciante > pt-br" e demorei mais de 2 mais de minutos pra perceber que **alguns** deles estão em português, não todos.

**Comment by fititnt** [comment]
Ok, vamos assumir que "pt-br", depois de dois minutos eu, que tenho experiência, imaginei que significava "Português do Brasil" e deduzi isso porque havia "en" mais abaixo. Eu fiquei frustado ao perceber que, agora até revisei, apenas 2 dos 10 primeiros projetos de "iniciante" que estão em "pt-br" não são "Português do Brasil".

Mesmo assumindo que este repositório está usando um código que máquinas e parte dos programadores assumem que significa a o idioma "Português do Brasil", eu fiquei frustrado ao perceber que talvez apenas 20% dos repositórios que são sugeridos estão em "Português do Brasil".

Assumindo isto, o uso de "pt-br" signifique "código feito por brasileiros" e não "Português do Brasil".

Por questões óbvias, **isto não tem nada haver com você, mas sim com as pessoas sugerindo repositórios sob uma tag que**, para quem realmente vai usar o repositório, deveriam por tudo em "en".

**Comment by fititnt** [comment]
Assumindo isto, creio que vou mudar minha opinião que citei ali no #11, pois se quase todos os projetos são em "en", não faz muito sentido manter esse repositório em "pt-br".

E um comentário extra: todas esses comentários que eu fiz eu ouvi de uma UX no passado, que me puxou orelha por "assumir que todo mundo entende pt-br". E eu também estava usando pt-br para uma coisa que não era bem o que eu achava que significava

**Comment by camilatigre** [comment]
Acho que a questão de confundir com as labels da lista pode ser resolvida com o que o @woliveiras falou de deixar a label em português. Como eu deixei em aberto as pessoas criaram em inglês. Acho que é mais claro `Português do Brasil` mas cara não conseguir entender `pt-br` é no mínimo complicado.

Obs: Ainda pode se criar uma legenda pras abreviações se isso virar algo realmente problemático.

**Comment by camilatigre** [comment]
@fititnt vou ler com calma seus últimos comentários depois. Se for o caso, você pode abrir pr com sugestões de mudança.

**Comment by kvnol** [comment]
E se, em vez de usar pt-br, usássemos flags? :brazil:
