### ISSUE TITLE
O uso de "</>" não é claro o suficiente na coluna que lista linguagem usadas

### ISSUE THREAD

**Issue by fititnt** [camilatigre/listamaravilhosaopensource#19]
A tabela que contém a lista de projetos-label-"</>" usa "</>" como cabeçalho para o que parece ser a linguagem.

O que é "</>"? Se significa "Linguagem de programação", por que abreviar com caracteres que não são claros o suficiente, e que, inclusive, são impronunciáveis para quem usa leitor de tela? Porque sim, existem programadores que não enxergam e usam leitores de tela para desenvolver, o cabeçalho desta tabela pode frustrar a leitura ou entender o significado

**Comment by camilatigre** [comment]
@fititnt a ideia era usar algum símbolo pra não ter que escrever algo tão grande como `Linguagem de Programação`. `</>` era referência a tags HTML. O que você sugere pra gente colocar como titulo que seja claro como `Linguagem de Programação` mas não tão grande?

**Comment by fititnt** [comment]
Eu pessoalmente usaria "Linguagem" ou "Linguagens"

**Comment by camilatigre** [comment]
Fechei antes de comentar. Fiz a alteração ((:
