### ISSUE TITLE
Sugestões de repositórios "pt-br" não são "pt-br"

### ISSUE THREAD

**Issue by fititnt** [camilatigre/listamaravilhosaopensource#20]
Baseado no comentário https://github.com/camilatigre/listamaravilhosaopensource/issues/18#issuecomment-238126450

------
Neste momento, das 10 primeiras sugestões na lista `Iniciante > pt-br` ao olhar o REAME.md do primeiro repositório que aparecer, estão em inglês, e pelo menos alguns deles, os commits e os issues.

Assumindo que, talvez, o foco do projeto é para iniciantes, isso **gera expectativa e posterior frustração, pois apenas 20% dos projetos são o que dá para entender**.

A pergunta é: **as pessoas que estão sugerindo projetos open source, estão usando `pt-br` como sinônimo de "projeto feito por nascidos no Brasil"?** Se sim, vocês concordam que isso é errado?

Creio que o mínimo que se espera é que, quem vai contribuir para o projeto de vocês que estão sob `pt-br` possa contribuir sem precisar saber inglês, em especial na hora de fazer Pull Request ou comentários nos Issues.

Se tudo é feito em inglês, por questão de lógica, é melhor que não estejam em "pt-br". Isto até limita pessoas que não sabem português.

**Comment by camilatigre** [comment]
@fititnt Entendi sua frustração mas, se me permite, achei esse titulo um pouco sensacionalista. Se estamos buscando solução nessa issue #21 e como você já havia abordado o problema nessa issue #18 . Entendo essa issue como redundante. Podemos fecha-la?

**Comment by fititnt** [comment]
Sim, não sabia que você ia criar logo em seguida um dedicado.

Quem tiver interesse, discute em #21, que até eu comentei.
