### ISSUE TITLE
Idiomas e Origem dos Projetos

### ISSUE THREAD

**Issue by camilatigre** [camilatigre/listamaravilhosaopensource#21]
Depois de ter confundido um contribuinte na questão idioma, origem do projeto e gerado frustração tive umas ideias para tentar organizar melhor isso.

Minhas ideias são: 
1. Tirar os projetos não brasileiros e colocar apenas projetos brasileiros e dividir por idioma
2. Deixar projetos não brasileiros e brasileiros, separar em páginas diferentes e deixar a divisão por idioma apenas
3. Adicionar  uma nova coluna na lista atual com a bandeira do país para indicar origem do projeto e passar os projetos que estão em inglês e são brasileiros para a área correta do idioma.

Qual a melhor solução? Alguma outra idea? Podem abrir PRs com proposta também.

**Comment by camilatigre** [comment]
@woliveiras @fititnt

**Comment by fititnt** [comment]
Bem, talvez o caso seja criar uma tabela única, onde tem uma indicação de "Origem" e "Idiomas aceitos" para issues e PRs, onde a ordem na coluna de idiomas dá ideia de qual a preferencia.

Para projetos grandes, ficariam uma bandera da ONU (ou um planeta) na origem, e idioma o "English".

Para para um projeto brasileiro, cujos mantenedores pode aceitar PRs de três idiomas, mas preferem em inglês, poderiam ficar

- Idioma: EN, PT, ES
- Origem: bandeira "brasil" 

Para um projeto cujo foco É publico que fala apenas português, até mesmo o código fonte sendo em português em vez de inglês, poderia ser

- Idioma: PT, EN
- Origem: bandeira "brasil"

**Comment by woliveiras** [comment]
Achei interessante esse esquema do @fititnt

**Comment by upcesar** [comment]
Olá pessoal. Também achei interessante o apontamento de @fititnt e ai eu poderia abrir e traduzir os projetos existentes para espanhol. Agora, caso o projeto esteja em vários idioma (seja multilinguagem) seria enquadrá-lo no idioma inglês? No idioma principal do autor? ou colocar uma coluna "Outros idiomas disponíveis"? Se aceitam sugestões.

**Comment by tiagoporto** [comment]
Pq não remove o idioma. Não faz sentido.

**Comment by omarkdev** [comment]
Acredito que a ideia do @fititnt é a mais sensata, já que me ocorreu a seguinte dúvida recentemente: Eu devo incluir um projeto em "pt-br" se a documentação dele é em Português do Brasil, ou se a origem dele é essa? Já que tem muitos projetos que preferimos criar uma documentação em inglês por maior abrangência, se pudessemos específicar isso na lista com certeza facilitaria muito.
