### ISSUE TITLE
Qual a melhor maneira de incluir um projeto com mais de uma linguagem

### ISSUE THREAD

**Issue by camilatigre** [camilatigre/listamaravilhosaopensource#3]

**Comment by woliveiras** [comment]
Daria pra adicionar as tecnologias separadas por vírgula.

Só precisa ter uma tabela das tecnologias pra que fique tudo normalizado, senão vai ter contribuidor escrevendo `ruby`, outro `Ruby`, `RUBY` e assim vai. kkkk

**Comment by camilatigre** [comment]
você fala ao lado de JS ficaria: ` JS, Ruby` por exemplo? não vai ficar uma coluna muito grande?

**Comment by woliveiras** [comment]
Verdade, se tiver muitas tecnologias fica mesmo. 😞
