### ISSUE TITLE
Labels em português

### ISSUE THREAD

**Issue by woliveiras** [camilatigre/listamaravilhosaopensource#7]
@camilatigre, como o projeto está em português, não seria melhor deixar as `labels` em pt-br também pra manter a consistência?

Ex.: good for beginner, bom para iniciantes

Mesmo que no repositório oficial esteja em inglês. :)

**Comment by camilatigre** [comment]
sim! você fala nos projetos pt-br, certo? como é um meio de filtro do github nos projetos en eu não quis traduzir as labels originais.

**Comment by woliveiras** [comment]
Isso, mas só na tabelinha aqui no repositório.

Entendi.

Acho que da pra deixar em inglês pra manter como lá então ein. 😄

**Comment by fititnt** [comment]
Bem, se você diz que algo está em português do Brasil e coloca uma palavra em inglês, você quebra expectativa, sem contar nos impactos na experiência do usuário.

Se **realmente** precisa fazer isso, é comum em documentos que envolvam HTML usar atributo `lang=XX` para palavras que tem contexto diferente e, visualmente, colocar palavra em italico para tudo que não for largamente conhecido pelo públoco alvo, algo muito aplicado em palavras de outro idioma.

Uma referência para o atributo lang está em https://www.w3.org/International/questions/qa-html-language-declarations

**Comment by camilatigre** [comment]
@fititnt o projeto trabalha só com markdown do github, não sei se o lang se encaixa. Projeto iniciou com a proposta de fazer pessoas iniciantes começarem a colaborar, saber por onde procurar e divulgar mais projetos brasileiros também (sendo eles em ptbr ou qualquer outra lingua). Se existem projetos gringos que estão em outra lingua ou em ptbr mas que estão sendo amigavéis com iniciantes por que não adicionar? acho que não quebra expectativa e sim abre o leque. Quem sabe inglês: ótimo. Quem não sabe tem opção também. 

Obs: Como ainda acho que tem pouco projeto e pouco idioma não vejo por que dividir mais.

**Comment by fititnt** [comment]
Markdown aceita HTML bruto além de _italico_. Alguns parsers de markdown vão transformar, por exemplo `<abbr title="Javascript">JS</abbr>` em algo que deixa claro qual a palavra completa da abreviação.

Os comentários em issues creio que não fazem isso, mas static generators certamente exportam e, se realmente quer usar palavras em inglês, é um modo de fazer isso.

**Comment by woliveiras** [comment]
Boa @fititnt 

Eu nem lembrava desse esquema do HTML + MD.
